# Generated by Django 4.1.7 on 2023-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='Images/user')),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('Age', models.IntegerField(null=True)),
                ('Phone', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
