# Generated by Django 4.1.6 on 2023-03-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminuser',
        ),
    ]
