# Generated by Django 4.1.7 on 2023-03-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_table1',
        ),
    ]
