# Generated by Django 4.1.7 on 2023-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0005_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
