# Generated by Django 4.1.6 on 2023-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0006_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('User2_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfield1', models.CharField(max_length=100, null=True)),
                ('cfield2', models.CharField(max_length=100, null=True)),
                ('cfield3', models.CharField(max_length=100, null=True)),
                ('cfield4', models.CharField(max_length=100, null=True)),
                ('cfield5', models.CharField(max_length=100, null=True)),
                ('cfield6', models.CharField(max_length=100, null=True)),
                ('cfield7', models.CharField(max_length=100, null=True)),
                ('cfield8', models.CharField(max_length=100, null=True)),
                ('cfield9', models.CharField(max_length=100, null=True)),
                ('cfield10', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'field_details',
            },
        ),
    ]
