# Generated by Django 4.1.6 on 2023-03-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0007_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user2',
            old_name='cfield1',
            new_name='cf1',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield10',
            new_name='cf10',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield2',
            new_name='cf2',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield3',
            new_name='cf3',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield4',
            new_name='cf4',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield5',
            new_name='cf5',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield6',
            new_name='cf6',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield7',
            new_name='cf7',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield8',
            new_name='cf8',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='cfield9',
            new_name='cf9',
        ),
    ]
