# Generated by Django 4.1.7 on 2023-03-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0008_rename_cfield1_user2_cf1_rename_cfield10_user2_cf10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
