# Generated by Django 4.1.7 on 2023-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0009_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.FileField(null=True, upload_to='Images/user'),
        ),
    ]
