# Generated by Django 4.1.7 on 2023-03-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0010_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Image',
            new_name='Profile_pic',
        ),
    ]
