# Generated by Django 4.1.7 on 2023-03-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0011_rename_image_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Profile_pic',
            new_name='Image',
        ),
    ]
