# Generated by Django 4.1.7 on 2023-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='Accuracy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user2',
            name='Classification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user2',
            name='Precision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user2',
            name='Recoll',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user2',
            name='cf11',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
