# Generated by Django 4.1.7 on 2023-07-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0014_user2_accuracy_user2_classification_user2_precision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user2',
            name='Accuracy',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='Classification',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='Precision',
        ),
        migrations.RemoveField(
            model_name='user2',
            name='Recoll',
        ),
    ]
