# Generated by Django 4.1.7 on 2023-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0015_remove_user2_accuracy_remove_user2_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.TextField(null=True),
        ),
    ]
