# Generated by Django 4.1.7 on 2023-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploaddataset',
            fields=[
                ('Upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.FileField(null=True, upload_to='Images/user')),
            ],
            options={
                'db_table': 'upload_details',
            },
        ),
    ]
