# Generated by Django 4.1.7 on 2023-03-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddataset',
            old_name='Upload_id',
            new_name='Admin_id',
        ),
        migrations.AddField(
            model_name='uploaddataset',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='uploaddataset',
            name='File_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploaddataset',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
