# Generated by Django 4.1.7 on 2023-03-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0002_rename_upload_id_uploaddataset_admin_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploaddataset',
            new_name='uploaddata',
        ),
    ]
