# Generated by Django 4.1.6 on 2023-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0005_alter_uploaddata_date_alter_uploaddata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='Image',
            field=models.FileField(db_column='Files', null=True, upload_to='Images/user'),
        ),
    ]
