# Generated by Django 4.1.6 on 2023-03-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0007_rename_image_uploaddata_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddata',
            old_name='File',
            new_name='Image',
        ),
    ]
