# Generated by Django 4.1.7 on 2023-07-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0012_svm'),
    ]

    operations = [
        migrations.CreateModel(
            name='KNN',
            fields=[
                ('KNN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'knn',
            },
        ),
        migrations.CreateModel(
            name='Naive_Bayes',
            fields=[
                ('NB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'naive_bayes',
            },
        ),
    ]
