# Generated by Django 4.1.7 on 2023-07-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0013_knn_naive_bayes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='Image',
            field=models.FileField(db_column='Files', null=True, upload_to='Dataset'),
        ),
    ]
