# Generated by Django 4.1.7 on 2023-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0014_alter_uploaddata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart_Data',
            fields=[
                ('HD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Age', models.TextField(max_length=100)),
                ('Sex', models.TextField(max_length=100)),
                ('ChestPainType', models.TextField(max_length=100)),
                ('RestingBP', models.TextField(max_length=100)),
                ('Cholesterol', models.TextField(max_length=100)),
                ('FastingBS', models.TextField(max_length=100)),
                ('RestingECG', models.TextField(max_length=100)),
                ('MaxHR', models.TextField(max_length=100)),
                ('ExerciseAngina', models.TextField(max_length=100)),
                ('Oldpeak', models.TextField(max_length=100)),
                ('ST_Slope', models.TextField(max_length=100)),
                ('HeartDisease', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'heart_data',
            },
        ),
    ]
