# Generated by Django 4.1.7 on 2023-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0015_heart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='svm',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
