# Generated by Django 4.1.7 on 2023-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0016_svm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontree',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knn',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logisticregression',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='naive_bayes',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='randomforest',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
