# Generated by Django 4.1.7 on 2023-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0017_decisiontree_name_knn_name_logisticregression_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_data',
            name='Age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heart_data',
            name='Cholesterol',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heart_data',
            name='FastingBS',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heart_data',
            name='HeartDisease',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heart_data',
            name='MaxHR',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heart_data',
            name='Oldpeak',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heart_data',
            name='RestingBP',
            field=models.IntegerField(max_length=100),
        ),
    ]
