# Generated by Django 4.1.7 on 2023-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0018_alter_heart_data_age_alter_heart_data_cholesterol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_data',
            name='Sex',
            field=models.IntegerField(max_length=100),
        ),
    ]
